### ISSUE TITLE
logging into SimplyE immediately after reactivating library card

### ISSUE THREAD

**Issue by daryanypl** [NYPL-Simplified/Simplified#60]
Problem occurred on my android app, but may require server-side involvement.

Steps to duplicate:
My NYC library card was expired.  I re-activated it.  Within 5 minutes of re-activating, I used the card number and pin to log into SimplyE.  The app allowed me to to log in, and to borrow open-source books, but not overdrive books.  On borrowing a drm-ed book, I'd get the acsm file, but the download would not complete. 

We hooked my phone to Aferdita's laptop, and she saw the following stack trace:

06-22 13:29:47.425  28561-28591/? E/org.nypl.simplified.books.core.BooksControllerBorrowTask﹕ [c982c6bb]: download failed: org.nypl.simplified.books.core.BookBorrowExceptionDRMWorkflowError: E_ACT_NOT_READY
           at org.nypl.simplified.books.core.BooksControllerBorrowTask$AdobeFulfillmentListener.onFulfillmentFailure(BooksControllerBorrowTask.java:868) ~[na:0.0]
           at org.nypl.drm.core.AdobeAdeptFulfillmentAdapter.onWorkflowError(AdobeAdeptFulfillmentAdapter.java:87) ~[na:0.0]
           at org.nypl.drm.adobe.AdobeAdeptConnector.nyadFulfillACSM(Native Method) ~[na:0.0]
           at org.nypl.drm.adobe.AdobeAdeptConnector.fulfillACSM(AdobeAdeptConnector.java:429) ~[na:0.0]
           at org.nypl.simplified.books.core.BooksControllerBorrowTask$2.executeWith(BooksControllerBorrowTask.java:271) ~[na:0.0]
           at org.nypl.drm.core.AdobeAdeptExecutor$3.run(AdobeAdeptExecutor.java:133) ~[na:0.0]
           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
           at org.nypl.drm.core.AdobeAdeptExecutor$1$1.run(AdobeAdeptExecutor.java:83) ~[na:0.0]
           at java.lang.Thread.run(Thread.java:818) ~[na:0.0]

We tried to log out of the SimplyE app, but the logout action would not go through.  Aferdita saw my account as not active.

We deleted SimplyE app from my phone, reinstalled it, re-entered my library card number and pin, and then I was able to check out, download, and read the overdrive book.

Actions needed:
- Give more instructive message to user.
- Do some server-side detecting to see if we start getting a lot of these.  The issue is rare, and not a priority right now, but when SimplyE gets popular, we might start having customers reactivate their cards and immediately try to download books.
- See if we can mitigate the logout issue, so don't have to reinstall simplye.

**Comment by aslagle** [comment]
Leonard fixed the server-side portion of this: https://github.com/NYPL-Simplified/circulation/pull/300

**Comment by aferditamuriqi** [comment]
do we need to test anything here? or can this be closed?

**Comment by aslagle** [comment]
my card's expired now so I can test this, if we plan exactly what I should test before I renew it. it's also out of device activations though, so I might only be able to test one device.
